services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - 8161:8161 # Web Console
      - 61616:61616 # Main Messaging Port
      - 1883:1883 # MQTT Port
      - 8883:8883 # MQTT Port with TLS
    # volumes: # Uncomment when using TLS
    # - ./certs:/etc/ssl/certs
    # - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    # environment:
    # - EXTRA_ARGS=--http-host 0.0.0.0 --relax-jolokia --ssl-key /etc/ssl/certs/le_keystore.jks --ssl-key-password securepass
    restart: unless-stopped

  mqtt-pg-logger:
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - artemis
      - timescaledb
    environment:
      - MQTT_HOST=artemis
      - MQTT_PORT=1883 # Set to 8883 when using TLS
      - MQTT_USER=artemis
      - MQTT_PASSWORD=artemis
      - DATABASE_HOST=timescaledb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - SSL_INSECURE=True # Set to False when using TLS
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped

volumes:
  artemis-config: