services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - 8161:8161 # Web Console
      - 61616:61616 # Main Messaging Port
      - 1883:1883 # MQTT Port
      - 8883:8883 # MQTT Port with TLS
    volumes:
    - ./certs:/etc/ssl/certs
    - ./etc-override:/var/lib/artemis-instance/etc-override # broker.xml override
    -  artemis-data:/var/lib/artemis-instance/data
    environment:
    - EXTRA_ARGS=--http-host 0.0.0.0 --relax-jolokia --ssl-key /etc/ssl/certs/[keystore.jks] --ssl-key-password [password] # Needed for Web Console HTTPs
    restart: unless-stopped

  mqtt-logger:
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - artemis
      - timescaledb
    environment:
      - MQTT_HOST=artemis.falk.host
      - MQTT_PORT=8883
      - MQTT_USER=artemis
      - MQTT_PASSWORD=artemis
      - DATABASE_HOST=timescaledb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - SSL_INSECURE=False
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  artemis-data:
  timescaledb-data: