name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          MQTT_USER: artemis
          MQTT_PASSWORD: artemis
          MQTT_CLIENT_ID: mqtt-logger-test
          MQTT_KEEPALIVE: "1"
          MQTT_DEFAULT_PROTOCOL: "5"
          MQTT_DEFAULT_QUALITY: "1"
          SSL_INSECURE: "true"
          CREATE_SCHEMA: "true"
          LOG_ALL_TOPICS: "false"
          ALLOW_ALL_TOPICS: "false"
          TESTCONTAINERS_RYUK_DISABLED: "true"
          FERNET_KEY: ${{ secrets.FERNET_KEY || 'D7jNgKGahOrZtQVd9reaT53B4SAz-gLH2ZJtRStpCsY=' }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL || 'admin@agritheory.dev' }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD || 'ohch4GeiSie' }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY || '59eggsXI2uU2eaWmmOcr_zMKfhE4rW-h0avo0IKNJS4' }}
        run: poetry run pytest -m "not benchmark"
